[workspace]
resolver = "2"
members = [
    "fluent-syntax",
    "fluent-bundle",
    "fluent-fallback",
    "fluent-resmgr",
    "fluent-pseudo",
    "fluent-testing",
    "fluent",
    "intl-memoizer"
]

exclude = [
    "fluent-cli",
]

[workspace.dependencies]
criterion = "0.3"
fluent-langneg = "0.14"
futures = "0.3"
iai = "0.1"
rustc-hash = "1"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = "1.0"
icu_locid = "1.4"
icu_plurals = { version = "1.4", features = ["experimental"] }
icu_provider = "1.4"

fluent-bundle = { path = "fluent-bundle" }
fluent-fallback = { path = "fluent-fallback" }
fluent-pseudo = { path = "fluent-pseudo" }
fluent-syntax = { path = "fluent-syntax" }
