[package]
name = "intl-memoizer"
description = """
A memoizer specifically tailored for storing lazy-initialized
intl formatters.
"""
version = "0.5.1"
edition = "2021"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Manish Goregaokar <manishsmail@gmail.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]
include = [
	"src/**/*",
	"benches/*.rs",
	"Cargo.toml",
	"README.md",
	"LICENSE-APACHE",
	"LICENSE-MIT"
]

[dependencies]
icu_locid = { workspace = true }
icu_plurals = { workspace = true }
icu_provider = { workspace = true }
type-map = "0.5"
hashbrown = "0.14"

[dev-dependencies]
fluent-langneg.workspace = true
criterion.workspace = true
icu_locid = "1.4"
icu_provider = "1.4"
icu_datetime = {version = "1.4", features = ["serde"]}
icu_calendar = "1.4"
icu_decimal = "1.4"
icu_provider_blob = "1.4"

[features]
default = []
sync = ["icu_provider/sync"]

[[bench]]
name = "single"
harness = false

